create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'customer'
    check (role in ('customer', 'owner')),
  created_at timestamptz not null default now()
);

create table public.snacks (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  color text not null default 'classic',
  weight text,
  image_url text,
  description text not null,
  icon text,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.site_settings (
  id integer primary key default 1,
  announcement text not null default '',
  hero_title text not null default '',
  hero_subtitle text not null default '',
  about_title text not null default '',
  about_body text not null default ''
);

insert into public.site_settings (id) values (1)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.snacks enable row level security;
alter table public.site_settings enable row level security;

create or replace function public.is_owner()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'owner'
  );
$$;

create policy "Anyone can read published snacks"
on public.snacks for select to anon, authenticated
using (is_published = true or public.is_owner());

create policy "Owners manage snacks"
on public.snacks for all to authenticated
using (public.is_owner()) with check (public.is_owner());

create policy "Anyone can read site settings"
on public.site_settings for select to anon, authenticated
using (true);

create policy "Owners update site settings"
on public.site_settings for update to authenticated
using (public.is_owner()) with check (public.is_owner());

create policy "Owners can upload product images"
on storage.objects for insert to authenticated
with check (bucket_id = 'product-images' and public.is_owner());

create policy "Owners can update product images"
on storage.objects for update to authenticated
using (bucket_id = 'product-images' and public.is_owner());

create policy "Owners can delete product images"
on storage.objects for delete to authenticated
using (bucket_id = 'product-images' and public.is_owner());
